name: Release
on:
  release:
    types:
      - published
  
jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.10"
      
      - name: Build package
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
